theme: jekyll-theme-minimal
title: [Catherine Hale]
description: [Personal Website]
logo: [https://github.com/halecatherine/halecatherine.github.io/blob/8a3f9f26368cf501c44ee0da126ec80f7a8e633d/Image.png]
